### PR TITLE
Add file NavMesheds

### PR DESCRIPTION
**Pull request by Antizombie**
I would like to add my "base" of the navigation grid to access it to everyone who wants to.
I think better, let it be as a general property.
Many people did it. Not only I am alone.

And if not mind, I will leave the advertisement of my server here.
[RZS] Russian zombie server + Bots
https://www.gametracker.com/server_info/195.2.76.204:27015
steam://connect/195.2.76.204:27015

### CODE REVIEW

**Comment by Dadido3** [comment]
I just added preview images so i can quickly check the new navmeshes you added and the changes you made to existing ones.

Overall the navmesh quality seems really good, so for the most part i can accept the files. From quickly glancing over the maps, there were some cases where handcrafted navmeshes were replaced with autogenerated ones. I need to check over these cases and then decide if i may keep the old one or not. But other than that your navmeshes are an improvement over most of the existing ones.

Thanks very much for the contribution, i'll fix the branch conflict that i accidentially caused, and then i'll probably merge this later today or on the weekend.

**Comment by Antizombie** [comment]
Thanks. It would be great to check the NavMesh data. I don't have much time to edit/check them now. I decided to give the NavMesh data so that others can use it and maybe also fix them. Yes, there are some with auto-generation, but they should be fully functional.

**Comment by Antizombie** [comment]
I didn't even know that you could do a "preview" to see without launching the game.

**Comment by Dadido3** [comment]
> I didn't even know that you could do a "preview" to see without launching the game.

There wasn't, i just added it this morning. ^^

**Pull request merged**
